// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIGHIYZB_Rm3lfsAJI5PBodxNSpYEqqjQ',
    appId: '1:913812268775:web:b9675b5102084c32d5a442',
    messagingSenderId: '913812268775',
    projectId: 'twitch-clone-b1541',
    authDomain: 'twitch-clone-b1541.firebaseapp.com',
    storageBucket: 'twitch-clone-b1541.firebasestorage.app',
    measurementId: 'G-SQGRPWR8SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgfFdvPOP5c6RVncV9V-jciCg0K8pKNO8',
    appId: '1:913812268775:android:21b3fb41e3bf7387d5a442',
    messagingSenderId: '913812268775',
    projectId: 'twitch-clone-b1541',
    storageBucket: 'twitch-clone-b1541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdL5oOiNGWb_n2SyqSYifZ8kDYc4RuDtU',
    appId: '1:913812268775:ios:cafdd259c76cf2c2d5a442',
    messagingSenderId: '913812268775',
    projectId: 'twitch-clone-b1541',
    storageBucket: 'twitch-clone-b1541.firebasestorage.app',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdL5oOiNGWb_n2SyqSYifZ8kDYc4RuDtU',
    appId: '1:913812268775:ios:cafdd259c76cf2c2d5a442',
    messagingSenderId: '913812268775',
    projectId: 'twitch-clone-b1541',
    storageBucket: 'twitch-clone-b1541.firebasestorage.app',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIGHIYZB_Rm3lfsAJI5PBodxNSpYEqqjQ',
    appId: '1:913812268775:web:7683e9c1fa1b92e4d5a442',
    messagingSenderId: '913812268775',
    projectId: 'twitch-clone-b1541',
    authDomain: 'twitch-clone-b1541.firebaseapp.com',
    storageBucket: 'twitch-clone-b1541.firebasestorage.app',
    measurementId: 'G-048CV2EM30',
  );
}
